name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  tests:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.10", "3.11", "3.12", "3.13"]
        django-version: ["4.2", "5.0"]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install "Django==${{ matrix.django-version }}.*"
          pip install -e .[dev]
      - name: Lint
        run: |
          ruff check .
      - name: Type check
        run: |
          mypy src
      - name: Run tests
        env:
          DJANGO_SETTINGS_MODULE: example.settings
        run: |
          pytest -q
